In [279]:
import pandas as pd 
import numpy as np

In [280]:
df_books=pd.read_csv('Books.csv')
df_user=pd.read_csv('Users.csv')
df_rating=pd.read_csv('Ratings.csv')

C:\Users\Shubham\AppData\Local\Temp\ipykernel_5396\1023404250.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_books=pd.read_csv('Books.csv')

In [281]:
df_books.shape,df_user.shape,df_rating.shape

((271360, 8), (278858, 3), (1149780, 3))

In [286]:
df_books['Book-Title'].unique().shape

(242135,)

In [288]:
df_user['User-ID'].unique().shape

(278858,)

In [6]:
df_books.info(),df_rating.info(),df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271359 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

(None, None, None)

In [7]:
df_books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
df_user.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
df_rating.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [15]:
df_books.head(3)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...

In [16]:
df_user.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [17]:
df_rating.head(3)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0

In [37]:
name_rating=df_rating.merge(df_books,on='ISBN')

In [42]:
df_num=name_rating.groupby('Book-Title').count()[['Book-Rating']]

In [43]:
df_num.columns=['num_of_books']

In [44]:
df_num

                                                    num_of_books
Book-Title
 A Light in the Storm: The Civil War Diary of A...             4
 Always Have Popsicles                                         1
 Apple Magic (The Collector's series)                          1
 Ask Lily (Young Women of Faith: Lily Series, B...             1
 Beyond IBM: Leadership Marketing and Finance f...             1
...                                                          ...
Ã?Â?lpiraten.                                                  2
Ã?Â?rger mit Produkt X. Roman.                                 4
Ã?Â?sterlich leben.                                            1
Ã?Â?stlich der Berge.                                          3
Ã?Â?thique en toc                                              2

[241071 rows x 1 columns]

In [49]:
df_avg_rating=name_rating.groupby('Book-Title')[['Book-Rating']].mean()

In [50]:
df_avg_rating

                                                    Book-Rating
Book-Title
 A Light in the Storm: The Civil War Diary of A...     2.250000
 Always Have Popsicles                                 0.000000
 Apple Magic (The Collector's series)                  0.000000
 Ask Lily (Young Women of Faith: Lily Series, B...     8.000000
 Beyond IBM: Leadership Marketing and Finance f...     0.000000
...                                                         ...
Ã?Â?lpiraten.                                          0.000000
Ã?Â?rger mit Produkt X. Roman.                         5.250000
Ã?Â?sterlich leben.                                    7.000000
Ã?Â?stlich der Berge.                                  2.666667
Ã?Â?thique en toc                                      4.000000

[241071 rows x 1 columns]

In [52]:
df_final=df_num.join(df_avg_rating)

In [54]:
df_final.reset_index(inplace=True)

In [57]:
df_final=df_final[df_final['num_of_books']>250]

In [62]:
df_final.sort_values('Book-Rating',ascending=False,inplace=True)

C:\Users\Shubham\AppData\Local\Temp\ipykernel_5396\1611249171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.sort_values('Book-Rating',ascending=False,inplace=True)

In [63]:
df_final

,Book-Title,num_of_books,Book-Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
...,...,...,...
227701,Vinegar Hill (Oprah's Book Club (Paperback)),265,2.245283
233635,Whispers,286,2.199301
143377,Presumed Innocent,294,2.139456
94382,Isle of Dogs,288,2.000000
234951,Wild Animus,2502,1.019584

In [201]:
df_popular=df_final.merge(df_books,on='Book-Title').drop_duplicates('Book-Title')

In [202]:
df_popular

,Book-Title,num_of_books,Book-Rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...
...,...,...,...,...,...,...,...,...,...,...
716,Vinegar Hill (Oprah's Book Club (Paperback)),265,2.245283,0380730138,A. Manette Ansay,1998,Perennial,http://images.amazon.com/images/P/0380730138.0...,http://images.amazon.com/images/P/0380730138.0...,http://images.amazon.com/images/P/0380730138.0...
717,Whispers,286,2.199301,0440216745,BELVA PLAIN,1994,Dell,http://images.amazon.com/images/P/0440216745.0...,http://images.amazon.com/images/P/0440216745.0...,http://images.amazon.com/images/P/0440216745.0...
727,Presumed Innocent,294,2.139456,0446359866,Scott Turow,1989,Warner Books,http://images.amazon.com/images/P/0446359866.0...,http://images.amazon.com/images/P/0446359866.0...,http://images.amazon.com/images/P/0446359866.0...
733,Isle of Dogs,288,2.000000,0425182908,Patricia Cornwell,2002,Berkley Publishing Group,http://images.amazon.com/images/P/0425182908.0...,http://images.amazon.com/images/P/0425182908.0...,http://images.amazon.com/images/P/0425182908.0...
739,Wild Animus,2502,1.019584,0971880107,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...

want to users who rates more than 200 movies (inteligent users) and books who have more than 50 ratings

In [ ]:
raters_user=

In [88]:
x=df_rating.groupby('User-ID').count()['ISBN']>200
inteligent_users=x[x].index

In [91]:
df_filter=name_rating[name_rating['User-ID'].isin(inteligent_users)]

In [93]:
df_filter.shape

(487671, 10)

In [82]:
df_rating.groupby('User-ID').count()['ISBN']>250

User-ID
2         False
7         False
8         False
9         False
10        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: ISBN, Length: 105283, dtype: bool

In [96]:
name_rating.columns

Index(['User-ID', 'ISBN', 'Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L'],
      dtype='object')

In [100]:
y=name_rating.groupby('Book-Title').count()['Book-Author']>50

In [103]:
popular_books=y[y].index

In [131]:
df_filter=df_filter[df_filter['Book-Title'].isin(popular_books)]

In [132]:
df_filter.columns

Index(['User-ID', 'ISBN', 'Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L'],
      dtype='object')

In [133]:
table=df_filter.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [134]:
k=df_filter['Book-Rating']!=0
k[k].shape

(27745,)

In [135]:
table.isnull().count()

User-ID
254       2381
2276      2381
2766      2381
2977      2381
3363      2381
          ...
275970    2381
277427    2381
277478    2381
277639    2381
278418    2381
Length: 896, dtype: int64

In [136]:
table.iloc[:,1:2][2276].isnull().count()

2381

In [137]:
table.shape

(2381, 896)

In [139]:
table.fillna(0,inplace=True)

In [147]:
table

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stardust,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [148]:
from sklearn.metrics.pairwise import cosine_similarity

In [150]:
cos=cosine_similarity(table)

In [191]:
set([i if 'Har' in i else 0 for i in table.index])

{0,
 'Angels Flight (Detective Harry Bosch Mysteries)',
 'Bitter Harvest',
 'Blindness (Harvest Book)',
 'Chesapeake Blue (Quinn Brothers (Hardcover))',
 'Confessions of a Sociopathic Social Climber : The Katya Livingston Chronicles (Katya Livingston Chronicles (Hardcover))',
 "Daughter of Fortune : A Novel (Oprah's Book Club (Hardcover))",
 'Good Harbor: A Novel',
 'Grave Secrets (Temperance Brennan Novel (Hardcover))',
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Hard Time (V.I. Warshawski Novels (Paperback))',
 'Harmful Intent',
 'Harriet the Spy',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'Harvest',
 'Inner Harbor (Quinn Brothers (Paperback))',
 'M Is for Malice (Kinsey Millhone Mysteries (Hardcover))',
 'N Is for Noose (Kinsey Millhone Mysteries (Hardcover))',
 'P Is for Peril (Kinsey Millhone Mysteries (Hardcover))',
 'Safe Harbor',
 'Soul Harvest: The World Takes Sides (Left Behind No. 4)',
 'Stone Kiss (Peter Decker &amp; Rina Lazarus Novels (Hardcover))',
 'The Concrete Blonde (A Harry Bosch Novel)',
 "The Deep End of the Ocean (Oprah's Book Club (Hardcover))",
 "The Pilot's Wife : A Novel Tag: Author of the Weight of Water (Oprah's Book Club (Hardcover))",
 "The Time Traveler's Wife (Harvest Book)",
 'Trunk Music (Detective Harry Bosch Mysteries)'}

In [170]:
np.where(table.index=='10 Lb. Penalty')[0][0]

0

In [154]:
arr=np.array([1,2,3])

In [157]:
np.where(arr==3)

(array([2], dtype=int64),)

In [255]:
def book_data(title):
    arr=df_books[df_books['Book-Title']=='Harry Potter and the Chamber of Secrets (Book 2)'].iloc[:1,:].values
#     print(arr)
#     return arr
    arr=arr[0]
    return [arr[2],arr[3],arr[7]]

In [245]:
df_books[df_books['Book-Title']=='Harry Potter and the Chamber of Secrets (Book 2)'].iloc[:1,:]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
3459,0439064872,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...

In [256]:
def find_similar(book):
    
    index=np.where(table.index==book)[0][0]
    
    s=[i[0] for i in sorted(list(enumerate(cos[index])),key=lambda x:x[1],reverse=True)[1:4]]
    
    return [book_data(table.index[x]) for x in s]

In [257]:
find_similar('Harry Potter and the Chamber of Secrets (Book 2)')

[['J. K. Rowling',
  2000,
  'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg'],
 ['J. K. Rowling',
  2000,
  'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg'],
 ['J. K. Rowling',
  2000,
  'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg']]

In [182]:
sorted(list(enumerate(cos[0])),key=lambda x:x[1],reverse=True)

[(0, 1.0),
 (490, 0.4634897582061269),
 (686, 0.43694983928441683),
 (504, 0.37358786588264326),
 (965, 0.3662505400886533),
 (2012, 0.3635642423874725),
 (1620, 0.34490732452138384),
 (2111, 0.3288382658013679),
 (1181, 0.32658038167850056),
 (1230, 0.31783424022533796),
 (1375, 0.28260240634765676),
 (1404, 0.2821910392572488),
 (1149, 0.26977154919387747),
 (2168, 0.2544919108926068),
 (20, 0.25437541957532156),
 (951, 0.2522731073332218),
 (1817, 0.2522731073332218),
 (403, 0.25171993131009057),
 (2353, 0.24257231046246674),
 (1358, 0.2414288129555069),
 (2221, 0.2411475835610753),
 (1065, 0.23784536654176383),
 (1636, 0.237141600400228),
 (272, 0.237040472976089),
 (221, 0.22685916827039443),
 (1487, 0.2246625242636544),
 (1071, 0.21976640824893562),
 (1717, 0.21971213823742808),
 (106, 0.21922946992470282),
 (753, 0.21517948312605892),
 (930, 0.214832544072678),
 (2252, 0.21029331637715773),
 (599, 0.20931383589477354),
 (384, 0.20491562567770288),
 (35, 0.2048826253351622),
 (123, 0.204173251443355),
 (2023, 0.2034627981431848),
 (1791, 0.20081013657273042),
 (1552, 0.20038722165859338),
 (1240, 0.20029852304236945),
 (1195, 0.19881397940129844),
 (1653, 0.19821721797661845),
 (1137, 0.19811893396439947),
 (118, 0.1935422171002805),
 (1876, 0.19081994477019087),
 (1628, 0.1890141129102927),
 (590, 0.18874458941325842),
 (1253, 0.18855127127413304),
 (183, 0.18672788195101142),
 (1005, 0.18642068003926798),
 (139, 0.1844621004544868),
 (1251, 0.18372458948774456),
 (841, 0.18369383514434626),
 (1495, 0.18337075178822865),
 (1692, 0.18206424730050408),
 (131, 0.18110013252465268),
 (1702, 0.18085181929248903),
 (1100, 0.18054633445933224),
 (826, 0.1804657480859773),
 (1696, 0.1792722971682669),
 (1687, 0.17861675041286185),
 (1141, 0.17856783126616863),
 (1499, 0.1777923681357857),
 (1880, 0.1762217143904252),
 (1488, 0.17542554407710234),
 (1559, 0.17456631175650997),
 (444, 0.17328879383880136),
 (2143, 0.17284623217932796),
 (2113, 0.17184951206094437),
 (1160, 0.17029765247377202),
 (525, 0.17018777592031523),
 (175, 0.17016308299209001),
 (417, 0.16986022637429588),
 (438, 0.16918769938965836),
 (1977, 0.16885901056015315),
 (1013, 0.1687570546739661),
 (1846, 0.1681516501608028),
 (88, 0.16756261430681652),
 (285, 0.16736182020915694),
 (617, 0.167316740932541),
 (2150, 0.16683582405952396),
 (379, 0.16677720742791818),
 (2239, 0.16494954037912768),
 (992, 0.15889085064887884),
 (2159, 0.15844625353660682),
 (320, 0.15628792235541927),
 (2234, 0.1562529435224236),
 (1505, 0.1550845759628043),
 (635, 0.15179659749609115),
 (858, 0.14996259902699338),
 (108, 0.14973499754072175),
 (655, 0.14952936457914406),
 (1464, 0.14812440716784905),
 (1785, 0.14811327105117295),
 (186, 0.14715864729025144),
 (1916, 0.1467614085485122),
 (1575, 0.14615201598468622),
 (885, 0.1459684972432393),
 (1825, 0.14564994642813892),
 (1642, 0.1454008442338035),
 (2209, 0.14499386225276398),
 (1109, 0.1449379350930749),
 (1090, 0.14466113698898445),
 (76, 0.1444037770888341),
 (2349, 0.14302540810140207),
 (1235, 0.1429456615615523),
 (476, 0.1428215228828508),
 (1173, 0.1427424693315302),
 (3, 0.14220116063684443),
 (1790, 0.1415584420599438),
 (258, 0.14115301099548644),
 (1720, 0.1409561447755621),
 (1454, 0.14034043526168188),
 (2059, 0.13967743821421588),
 (1670, 0.13871228507702843),
 (2171, 0.1381756715383275),
 (1084, 0.136091454483223),
 (1987, 0.13557222783332862),
 (1699, 0.13509820846978662),
 (996, 0.13434677220255703),
 (1966, 0.1338734243818203),
 (251, 0.1338263438724052),
 (387, 0.13241579759844996),
 (1304, 0.13219253100610218),
 (1249, 0.1320614711740018),
 (958, 0.13196768870723902),
 (1750, 0.13109150652452387),
 (282, 0.13079461930974653),
 (949, 0.1300808949825722),
 (1291, 0.12986419433650892),
 (1248, 0.12836206951022322),
 (1673, 0.1274984994112574),
 (905, 0.12745455713891618),
 (400, 0.12734222711273163),
 (548, 0.12667629320371657),
 (1187, 0.1257313681045108),
 (886, 0.12530396005507313),
 (1014, 0.12484281122411908),
 (2284, 0.12463631492576845),
 (595, 0.12429597192776372),
 (1256, 0.12428918183888221),
 (1701, 0.12422509707768613),
 (261, 0.1239665638170606),
 (628, 0.12391813957745301),
 (1347, 0.12257715436366888),
 (1491, 0.12254179542058356),
 (2152, 0.12237469108208024),
 (242, 0.12232455007614032),
 (2093, 0.1212976218316605),
 (190, 0.11978134195421053),
 (1221, 0.11849487167035033),
 (1906, 0.11844384394746289),
 (2248, 0.11787488590126037),
 (552, 0.11764292460221706),
 (2343, 0.11756970769107535),
 (1806, 0.11557891341771462),
 (2282, 0.11544126255548069),
 (1142, 0.11527716686122196),
 (1030, 0.11519538099291932),
 (2277, 0.11509593942898855),
 (1731, 0.11495106389711221),
 (1709, 0.11489022712974065),
 (36, 0.11468687361129627),
 (1852, 0.11463259330751253),
 (278, 0.11437948395742846),
 (1890, 0.11395326134770471),
 (263, 0.1133525546787598),
 (316, 0.11182358135825585),
 (2214, 0.11114279370329998),
 (1693, 0.11053489783891633),
 (1544, 0.11008318181141186),
 (2048, 0.11004643749614541),
 (1800, 0.11003045963680107),
 (2354, 0.10982895420552334),
 (354, 0.10966668528527711),
 (1710, 0.10949170304326071),
 (2280, 0.10939997110671174),
 (1694, 0.10875195999967709),
 (1263, 0.10789224722650828),
 (29, 0.10780320775878946),
 (768, 0.1076072629371082),
 (1057, 0.10749329682215472),
 (1239, 0.10661476127669592),
 (2187, 0.10527670212444001),
 (1450, 0.10495807127050445),
 (2324, 0.10472739566012901),
 (527, 0.10423847480129568),
 (177, 0.10407993710528399),
 (1707, 0.10390736206183952),
 (295, 0.10366719283383216),
 (1886, 0.10338643598072515),
 (555, 0.10314936893855274),
 (962, 0.10291068901451797),
 (89, 0.10270516780821001),
 (1038, 0.10241113910653354),
 (2094, 0.10136074068201148),
 (430, 0.10114579613065204),
 (1381, 0.10111581273583052),
 (1747, 0.10088991560454309),
 (59, 0.10082696877127466),
 (2264, 0.10043914705429707),
 (1588, 0.1003527022722734),
 (1680, 0.10034991217837498),
 (901, 0.09933243900816847),
 (1539, 0.09927650277453774),
 (791, 0.09893063032675364),
 (1910, 0.09852175280933236),
 (1342, 0.09790496469102487),
 (967, 0.09780280609621829),
 (2131, 0.09770495433975641),
 (257, 0.09769249435700604),
 (560, 0.09728627714805368),
 (2060, 0.09704606477292675),
 (1470, 0.09619534269888892),
 (1389, 0.09583034459002436),
 (796, 0.09582507356336842),
 (292, 0.09517700230409909),
 (2253, 0.09501154889380496),
 (1965, 0.0949304047736294),
 (959, 0.09438880731263585),
 (785, 0.09415685492333008),
 (98, 0.09260046910104897),
 (1088, 0.09244932616919498),
 (1952, 0.09140577464502453),
 (2304, 0.09113434953720674),
 (2223, 0.09007673692001653),
 (1989, 0.08994470100809439),
 (1925, 0.08992353505862893),
 (1337, 0.08987487272208386),
 (1437, 0.08893668598664865),
 (1504, 0.08887434521861236),
 (1997, 0.08886946806688886),
 (1062, 0.08886672534932938),
 (1727, 0.08850917586658448),
 (1482, 0.08803918000889686),
 (1721, 0.08783322080987785),
 (287, 0.08743855833484239),
 (1946, 0.08685979126787816),
 (279, 0.08678982767113061),
 (90, 0.08599109217703026),
 (247, 0.08583057311761454),
 (2367, 0.08570381975537485),
 (1398, 0.0855613819350195),
 (757, 0.0850609759929779),
 (1383, 0.084468974921464),
 (1908, 0.08412778329500328),
 (1604, 0.08406941576561369),
 (342, 0.08368091010457847),
 (333, 0.08288405034412301),
 (72, 0.08279508297669264),
 (1072, 0.0825699984431589),
 (906, 0.08193536019004075),
 (1667, 0.08157122109725176),
 (1428, 0.08145366665541554),
 (1638, 0.08081337496679634),
 (769, 0.08048241724734302),
 (495, 0.07993011209593702),
 (805, 0.07974461699875159),
 (705, 0.07931176872688436),
 (642, 0.0789038687369164),
 (766, 0.07811451743157699),
 (1730, 0.07728361271850957),
 (2123, 0.07665786654112576),
 (1715, 0.07663133673706385),
 (2117, 0.07608121757730471),
 (1929, 0.07518237603304387),
 (1234, 0.0747989073690893),
 (2281, 0.07470916659608139),
 (1928, 0.07469010890078243),
 (1289, 0.07459564530971072),
 (1979, 0.07405663552558649),
 (1184, 0.07377373843469295),
 (2056, 0.07353371208855153),
 (149, 0.07329390898796614),
 (298, 0.07256583832734997),
 (821, 0.07249693112638199),
 (1864, 0.07236423695804839),
 (1939, 0.07234189543984741),
 (701, 0.07231434447013185),
 (762, 0.07223289043710689),
 (37, 0.07197225581999338),
 (549, 0.07159694165492812),
 (920, 0.0713254128856014),
 (1308, 0.07129543334465258),
 (319, 0.06984343841779396),
 (429, 0.06928252456129212),
 (2127, 0.06833809390519632),
 (944, 0.06829110808816821),
 (1756, 0.06790294344996141),
 (165, 0.06758582750083703),
 (366, 0.0675348317144108),
 (2279, 0.06752543691401963),
 (2265, 0.06658505126712731),
 (1376, 0.06644136222180053),
 (85, 0.06586342732667318),
 (2217, 0.06545328568535093),
 (1761, 0.06485258303889421),
 (307, 0.06474701717991413),
 (329, 0.06463364309110622),
 (2040, 0.06313542076463147),
 (1294, 0.061983281908530315),
 (1969, 0.0619366573916146),
 (1525, 0.061762535416163965),
 (2103, 0.06091303491833112),
 (6, 0.06020032116692132),
 (1719, 0.06018211148644409),
 (2104, 0.05999871609059447),
 (843, 0.059703688719266734),
 (2082, 0.05957894337819157),
 (2181, 0.05915781059928102),
 (376, 0.05836678565476913),
 (2086, 0.05825997857125558),
 (2190, 0.05816698572894273),
 (1842, 0.058146825988727696),
 (2028, 0.05765729192145988),
 (2027, 0.057605847930459954),
 (1179, 0.05724045721315804),
 (897, 0.05691617799828995),
 (204, 0.055525864567657325),
 (75, 0.05550465330695963),
 (1674, 0.05507057835659115),
 (1199, 0.05504511210270955),
 (1725, 0.05453150752072366),
 (1201, 0.054471820476619005),
 (372, 0.05390088057667162),
 (1766, 0.05355078035220674),
 (770, 0.05025961552020383),
 (1677, 0.05007280388003757),
 (883, 0.04950101215522303),
 (1292, 0.049005860521139),
 (1485, 0.04899731220749415),
 (441, 0.04891195494478674),
 (2378, 0.04850195490667907),
 (1879, 0.04727209350122004),
 (738, 0.04561594897440673),
 (2251, 0.044932688939092684),
 (1286, 0.04489631942599797),
 (739, 0.04314454064363337),
 (1099, 0.04281189840398862),
 (1650, 0.04275602316869655),
 (771, 0.04246884274066216),
 (767, 0.04204004428110267),
 (698, 0.0414384594384934),
 (678, 0.041036747675265633),
 (1945, 0.04069329115649772),
 (936, 0.04052089902864648),
 (1591, 0.03989657497652882),
 (937, 0.03927886953985194),
 (899, 0.03925657100297686),
 (957, 0.03786200639413054),
 (537, 0.03740293070601521),
 (193, 0.03515771972374294),
 (626, 0.03442978938215892),
 (2134, 0.0340241377827208),
 (1753, 0.03304866862171528),
 (143, 0.032748503820843586),
 (506, 0.032125191096344256),
 (1811, 0.031896131553611894),
 (1581, 0.030494666513788387),
 (1078, 0.029286603259958115),
 (1881, 0.023885006010123142),
 (1321, 0.023854101230887877),
 (2297, 0.021140534425872767),
 (2146, 0.02105629538057368),
 (503, 0.01953122769428766),
 (929, 0.015174751183525115),
 (1, 0.0),
 (2, 0.0),
 (4, 0.0),
 (5, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (73, 0.0),
 (74, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.0),
 (80, 0.0),
 (81, 0.0),
 (82, 0.0),
 (83, 0.0),
 (84, 0.0),
 (86, 0.0),
 (87, 0.0),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (99, 0.0),
 (100, 0.0),
 (101, 0.0),
 (102, 0.0),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (107, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (135, 0.0),
 (136, 0.0),
 (137, 0.0),
 (138, 0.0),
 (140, 0.0),
 (141, 0.0),
 (142, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.0),
 (150, 0.0),
 (151, 0.0),
 (152, 0.0),
 (153, 0.0),
 (154, 0.0),
 (155, 0.0),
 (156, 0.0),
 (157, 0.0),
 (158, 0.0),
 (159, 0.0),
 (160, 0.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0),
 (170, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0),
 (176, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (184, 0.0),
 (185, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.0),
 (191, 0.0),
 (192, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (205, 0.0),
 (206, 0.0),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (213, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.0),
 (222, 0.0),
 (223, 0.0),
 (224, 0.0),
 (225, 0.0),
 (226, 0.0),
 (227, 0.0),
 (228, 0.0),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.0),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (240, 0.0),
 (241, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (259, 0.0),
 (260, 0.0),
 (262, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (273, 0.0),
 (274, 0.0),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (280, 0.0),
 (281, 0.0),
 (283, 0.0),
 (284, 0.0),
 (286, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (293, 0.0),
 (294, 0.0),
 (296, 0.0),
 (297, 0.0),
 (299, 0.0),
 (300, 0.0),
 (301, 0.0),
 (302, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.0),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (311, 0.0),
 (312, 0.0),
 (313, 0.0),
 (314, 0.0),
 (315, 0.0),
 (317, 0.0),
 (318, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.0),
 (363, 0.0),
 (364, 0.0),
 (365, 0.0),
 (367, 0.0),
 (368, 0.0),
 (369, 0.0),
 (370, 0.0),
 (371, 0.0),
 (373, 0.0),
 (374, 0.0),
 (375, 0.0),
 (377, 0.0),
 (378, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (385, 0.0),
 (386, 0.0),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.0),
 (399, 0.0),
 (401, 0.0),
 (402, 0.0),
 (404, 0.0),
 (405, 0.0),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.0),
 (411, 0.0),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (431, 0.0),
 (432, 0.0),
 (433, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (439, 0.0),
 (440, 0.0),
 (442, 0.0),
 (443, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (457, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.0),
 (468, 0.0),
 (469, 0.0),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (491, 0.0),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.0),
 (501, 0.0),
 (502, 0.0),
 (505, 0.0),
 (507, 0.0),
 (508, 0.0),
 (509, 0.0),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (526, 0.0),
 (528, 0.0),
 (529, 0.0),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (535, 0.0),
 (536, 0.0),
 (538, 0.0),
 (539, 0.0),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (550, 0.0),
 (551, 0.0),
 (553, 0.0),
 (554, 0.0),
 (556, 0.0),
 (557, 0.0),
 (558, 0.0),
 (559, 0.0),
 (561, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (566, 0.0),
 (567, 0.0),
 (568, 0.0),
 (569, 0.0),
 (570, 0.0),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0),
 (581, 0.0),
 (582, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (588, 0.0),
 (589, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (596, 0.0),
 (597, 0.0),
 (598, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (615, 0.0),
 (616, 0.0),
 (618, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (627, 0.0),
 (629, 0.0),
 (630, 0.0),
 (631, 0.0),
 (632, 0.0),
 (633, 0.0),
 (634, 0.0),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (656, 0.0),
 (657, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.0),
 (685, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0),
 (690, 0.0),
 (691, 0.0),
 (692, 0.0),
 (693, 0.0),
 (694, 0.0),
 (695, 0.0),
 (696, 0.0),
 (697, 0.0),
 (699, 0.0),
 (700, 0.0),
 (702, 0.0),
 (703, 0.0),
 (704, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.0),
 (711, 0.0),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.0),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (723, 0.0),
 (724, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.0),
 (731, 0.0),
 (732, 0.0),
 (733, 0.0),
 ...]

In [179]:
a=[1,3,2]

In [180]:
sorted(a,k)

[1, 2, 3]

In [195]:
popular_books

Index(['10 Lb. Penalty', '16 Lighthouse Road', '1984', '1st to Die: A Novel',
       '2010: Odyssey Two', '204 Rosewood Lane', '2061: Odyssey Three',
       '24 Hours', '2nd Chance', '3rd Degree',
       ...
       'YOU BELONG TO ME', 'Year of Wonders', 'You Belong To Me',
       'You Shall Know Our Velocity', 'Young Wives',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"',
       '\Surely You're Joking, Mr. Feynman!\": Adventures of a Curious Character"',
       'stardust'],
      dtype='object', name='Book-Title', length=2381)

In [199]:
df_popular=df_books[df_books['Book-Title'].isin(popular_books)]

In [200]:
df_popular.drop_duplicates()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
14,1558746218,A Second Chicken Soup for the Woman's Soul (Ch...,Jack Canfield,1998,Health Communications,http://images.amazon.com/images/P/1558746218.0...,http://images.amazon.com/images/P/1558746218.0...,http://images.amazon.com/images/P/1558746218.0...
18,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...
19,0452264464,Beloved (Plume Contemporary Fiction),Toni Morrison,1994,Plume,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...
26,0971880107,Wild Animus,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...
...,...,...,...,...,...,...,...,...
270710,0523416873,The Presence,Yvonne MacManus,1982,Pinnacle Books,http://images.amazon.com/images/P/0523416873.0...,http://images.amazon.com/images/P/0523416873.0...,http://images.amazon.com/images/P/0523416873.0...
270954,0399150684,Naked Prey,John Sandford,2003,Putnam Berkley Audio,http://images.amazon.com/images/P/0399150684.0...,http://images.amazon.com/images/P/0399150684.0...,http://images.amazon.com/images/P/0399150684.0...
271055,087004124X,Anthem,Ayn Rand,1966,Caxton Press,http://images.amazon.com/images/P/087004124X.0...,http://images.amazon.com/images/P/087004124X.0...,http://images.amazon.com/images/P/087004124X.0...
271169,0395647398,"The Two Towers (The Lord of the Rings, Part 2)",J. R. R. Tolkien,1992,Houghton Mifflin,http://images.amazon.com/images/P/0395647398.0...,http://images.amazon.com/images/P/0395647398.0...,http://images.amazon.com/images/P/0395647398.0...
271315,1902852036,All the Queen's Men,Nick Elwood,1999,Gay Men's Press,http://images.amazon.com/images/P/1902852036.0...,http://images.amazon.com/images/P/1902852036.0...,http://images.amazon.com/images/P/1902852036.0...

In [225]:
df_50=df_popular.iloc[:,:51]

In [226]:
df_50['rating']=df_50['Book-Rating'].apply(lambda x: round(x,2))

In [228]:
df_50=df_50[['Book-Title','Book-Author','Image-URL-L','rating','Year-Of-Publication']]

In [229]:
df_50.columns=['title','author','url','rating','year']

In [230]:
df_50.columns

Index(['title', 'author', 'url', 'rating', 'year'], dtype='object')

In [231]:
import pickle

In [259]:
with open('cos_data.pkl','wb') as f:
    pickle.dump(cos,f)

In [220]:
with open('top.pkl','rb') as c:
    var=pickle.load(c)

In [223]:
var['title'].values

array(['Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       "Harry Potter and the Sorcerer's Stone (Book 1)",
       'Harry Potter and the Order of the Phoenix (Book 5)',
       'Harry Potter and the Chamber of Secrets (Book 2)',
       'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
       'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
       "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
       'The Two Towers (The Lord of the Rings, Part 2)',
       'To Kill a Mockingbird', 'The Da Vinci Code',
       'The Five People You Meet in Heaven', 'The Catcher in the Rye',
       'The Lovely Bones: A Novel', '1984', 'Prodigal Summer: A Novel',
       'Neverwhere', 'The Secret Life of Bees',
       'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
       "Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
       'The Red Tent (Bestselling Backlist)',
       "The Hitchhiker's Guide to the Galaxy",
       'Nickel and Dimed: On (Not) Getting By in America',
       'Into the Wild', 'Fahrenheit 451', 'Girl with a Pearl Earring',
       'Outlander', "Where the Heart Is (Oprah's Book Club (Paperback))",
       'Seabiscuit: An American Legend', 'Life of Pi', 'The Bean Trees',
       'A Child Called \\It\\": One Child\'s Courage to Survive"',
       "ANGELA'S ASHES", 'Good in Bed',
       'Fast Food Nation: The Dark Side of the All-American Meal',
       'American Gods', 'Skipping Christmas',
       "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
       'The Golden Compass (His Dark Materials, Book 1)',
       'The Color Purple', 'Silence of the Lambs', 'About a Boy',
       'Seven Up (A Stephanie Plum Novel)',
       'The Alchemist: A Fable About Following Your Dream',
       'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
       "Suzanne's Diary for Nicholas", 'Lord of the Flies',
       'A Prayer for Owen Meany',
       'The Vampire Lestat (Vampire Chronicles, Book II)',
       "White Oleander : A Novel (Oprah's Book Club)",
       'Wicked: The Life and Times of the Wicked Witch of the West',
       'Me Talk Pretty One Day', 'Timeline', 'Misery',
       'Angels &amp; Demons', 'Bel Canto: A Novel', 'Watership Down',
       'The Green Mile',
       'Balzac and the Little Chinese Seamstress : A Novel',
       'One for the Money (Stephanie Plum Novels (Paperback))',
       'Confessions of a Shopaholic (Summer Display Opportunity)',
       'Empire Falls', 'Lucky : A Memoir',
       'The Poisonwood Bible: A Novel', 'Red Dragon',
       "The Pilot's Wife : A Novel", 'Insomnia',
       'Digital Fortress : A Thriller', '1st to Die: A Novel',
       "She's Come Undone (Oprah's Book Club)", 'The Notebook',
       'Interview with the Vampire', 'The Nanny Diaries: A Novel',
       "Bridget Jones's Diary", 'White Oleander : A Novel',
       'The Poisonwood Bible',
       "She's Come Undone (Oprah's Book Club (Paperback))",
       'Two for the Dough',
       'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
       'Fried Green Tomatoes at the Whistle Stop Cafe', 'The Summons',
       'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
       'Jurassic Park', 'A Heartbreaking Work of Staggering Genius',
       'Girl, Interrupted',
       "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
       'Chocolat', 'A Walk to Remember', "The Handmaid's Tale",
       "The Bonesetter's Daughter", 'One Door Away from Heaven',
       'Fall On Your Knees (Oprah #45)', 'A Bend in the Road',
       'Summer Sisters', 'Cold Mountain : A Novel', 'The Beach House',
       'The Hours: A Novel', 'Icy Sparks',
       "Angela's Ashes (MMP) : A Memoir", 'How to Be Good',
       'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
       'The Partner', 'The God of Small Things',
       'The Witching Hour (Lives of the Mayfair Witches)',
       'Dance upon the Air (Three Sisters Island Trilogy)', '2nd Chance',
       'Little Altars Everywhere: A Novel', 'SHIPPING NEWS',
       'Snow Falling on Cedars', 'The Rescue', 'A Painted House',
       'Unnatural Exposure', 'Dreamcatcher', 'Dolores Claiborne',
       'Point of Origin', 'The Testament', 'I Know This Much Is True',
       'Midnight in the Garden of Good and Evil: A Savannah Story',
       "The Girls' Guide to Hunting and Fishing", 'Cradle and All',
       'A Time to Kill', 'The Last Time They Met : A Novel',
       'Along Came a Spider (Alex Cross Novels)', 'Midwives: A Novel',
       'The Bridges of Madison County', 'The Client', 'The Firm',
       'The Smoke Jumper', 'The Joy Luck Club',
       "Full House (Janet Evanovich's Full Series)",
       'Pop Goes the Weasel', 'The King of Torts', 'Tara Road',
       'House of Sand and Fog', 'The Chamber', 'The Reader',
       'The Blind Assassin', 'STONES FROM THE RIVER',
       "The Kitchen God's Wife", '\\O\\" Is for Outlaw"', 'The Hot Zone',
       'The Cider House Rules', 'The Alienist', 'Violets Are Blue',
       'Deception Point', 'The Rainmaker', 'Mystic River', 'Airframe',
       'The Runaway Jury', 'All I Really Need to Know',
       'The Last Precinct', 'We Were the Mulvaneys', 'The Lost World',
       'The Street Lawyer', 'The Brethren', 'The Hundred Secret Senses',
       'Kiss the Girls', 'Black and Blue', 'A Widow for One Year',
       'Black Notice', 'Message in a Bottle', 'Flesh and Blood',
       'Hannibal', 'Sphere',
       'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
       'When the Wind Blows',
       'The Queen of the Damned (Vampire Chronicles (Paperback))',
       'The Horse Whisperer', 'Back Roads',
       "The Book of Ruth (Oprah's Book Club (Paperback))",
       'Scarlet Feather', 'Lightning', 'Cause of Death',
       'The Pelican Brief', 'While I Was Gone',
       'The Perfect Storm : A True Story of Men Against the Sea',
       'A Map of the World', 'Rising Sun', 'Congo', 'The Prince of Tides',
       'Disclosure', "Vinegar Hill (Oprah's Book Club (Paperback))",
       'Whispers', 'Presumed Innocent', 'Isle of Dogs', 'Wild Animus'],
      dtype=object)

In [224]:
pd.__version__

'1.5.2'

In [267]:
df_c=pd.read_csv('tmdb_5000_credits.csv')

In [268]:
df_m=pd.read_csv('tmdb_5000_movies.csv')

In [269]:
df_m.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [270]:
df_c.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [277]:
import ast

In [278]:
ast.literal_eval(df_c['crew'].values[0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},